desc: "Xen-Troops development setup for Renesas RCAR Gen3 hardware"
min_ver: "0.2"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOMD_BUILD_DIR: "build-domd"
  DOMF_BUILD_DIR: "build-domf"
  XT_DOMD_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domd.dtb"
  XT_DOMU_DTB_NAME: "salvator-generic-domu.dtb"
  XT_DOMA_DTB_NAME: ""
  XT_XEN_DTB_NAME: "r8a77951-h3ulcb-4x2g-ab-xen.dtb"
  XT_PVR_NUM_OSID: "2"
  XT_OP_TEE_FLAVOUR: "generic_dt"
  XT_GENERIC_DOMU_TAG: "domf"
  XT_DOMA_TAG: ""
  MACHINE: "h3ulcb"
  SOC_FAMILY: "r8a7795"
  XT_DOMD_CONFIG_NAME: "domd.cfg"
  XT_DOMU_CONFIG_NAME: "domf.cfg"
  XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
  XT_DOMD_DTB_NAME: "r8a77951-h3ulcb-4x2g-ab-domd.dtb"

common_data:
  # Sources used by all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "git://git.yoctoproject.org/poky"
      rev: dunfell
    - type: git
      url: "git://git.openembedded.org/meta-openembedded"
      rev: dunfell
    - type: git
      url: "git://git.yoctoproject.org/meta-virtualization"
      rev: dunfell
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
      rev: master
    - type: git
      url: "https://github.com/xen-troops/meta-xt-rcar.git"
      rev: master
    - type: git
      url: "https://git.linaro.org/openembedded/meta-linaro.git"
      rev: dunfell      
 
  # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../common_data/downloads"]

    # Skip warning about missing "virtualization" distro feature
    - [SKIP_META_VIRT_SANITY_CHECK, "1"]

    # Use hypervisor console on all guests
    - [SERIAL_CONSOLES, "115200;hvc0"]

    # Configure number of supported GPU virtual guests
    - [XT_PVR_NUM_OSID, "%{XT_PVR_NUM_OSID}"]

    # Remove features that we are not using
    - [DISTRO_FEATURES_remove, "x11 gtk gobject-introspection-data wifi nfc bluetooth irda zeroconf 3g sysvinit"]

domd_domu_conf: &DOMD_DOMU_CONF
    - [MACHINE, "%{MACHINE}"]
    - [SOC_FAMILY, "%{SOC_FAMILY}"]

    # Add systemd configuration
    - [DISTRO_FEATURES_append, " systemd"]
    - [DISTRO_FEATURES_append, " pam"]
    - [DISTRO_FEATURES_append, " ivi-shell"]
    - [DISTRO_FEATURES_append, " virtualization"]
    - [PACKAGE_CLASSES, "package_ipk"]
    - [BB_DANGLINGAPPENDS_WARNONLY, "yes"]
    - [DEFAULT_TIMEZONE, "US/Pacific"]
    - [XT_GUESTS_INSTALL, "%{XT_GENERIC_DOMU_TAG} domd"]
    - [DISTRO_FEATURES_remove, "ivi-shell opengl wayland vulkan pulseaudio"]
        # Add for gstreamer plugins ugly
    - [LICENSE_FLAGS_WHITELIST, "commercial"]

    # Configuration for USB 3.0
    # TODO: Enable this after validation
    #- [MACHINE_FEATURES_append, " usb3"]

    # Add Capacity Aware migration Strategy (CAS)
    - [MACHINE_FEATURES_append, " cas"]

    # Remove ptest to reduce the build time
    - [DISTRO_FEATURES_remove, "ptest"]

  # The same set of layers and configs is used both in DomD and DomU
  # to build a DDK from source code
  
ddk_source_overrides: &DDK_SOURCE_OVERRIDES
  sources:
    - type: git
      url: "git://git.openembedded.org/meta-python2"
      rev: dunfell
    - type: git
      url: "https://github.com/kraj/meta-clang"
      rev: dunfell
    - type: git
      url: "ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary"
      rev: "ef1aa566d74a11c4d2ae9592474030a706b4cf39"
      dir: "proprietary"
  builder:
    conf:
      - [GLES_VERSION, "1.11"]
      - [PREFERRED_PROVIDER_gles-user-module,          "gles-user-module"]
      - [PREFERRED_VERSION_gles-user-module,           "${GLES_VERSION}"]
      - [PREFERRED_PROVIDER_kernel-module-gles,        "kernel-module-gles"]
      - [PREFERRED_VERSION_kernel-module-gles,         "${GLES_VERSION}"]
      - [PREFERRED_PROVIDER_gles-module-egl-headers,   "gles-module-egl-headers"]
      - [PREFERRED_VERSION_gles-module-egl-headers,    "${GLES_VERSION}"]
    layers:
      - "../meta-python2"
      - "../meta-clang"
      - "../meta-xt-rcar/meta-xt-rcar-proprietary"
        
components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "https://github.com/iusyk/meta-xt-prod-aos.git"
        rev: moulin
      
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "generic-armv8-xt"]
        - [XT_DOMD_CONFIG_NAME, "%{XT_DOMD_CONFIG_NAME}"]
        - [XT_DOMU_CONFIG_NAME, "%{XT_DOMU_CONFIG_NAME}"]
        - [XT_DOMD_DTB_NAME, "%{XT_DOMD_DTB_NAME}"]
        - [XT_DOMU_DTB_NAME, "%{XT_DOMU_DTB_NAME}"]
        - [XT_DOM_NAME, "dom0"]
        - [XT_GUEST_INSTALL, "%{XT_GENERIC_DOMU_TAG} domd"]
        - [XT_DOMF_CONFIG_NAME, "domf.cfg"]

        # Disable HWDB which quite huge (around 15MB) and is not required at all
        - [BAD_RECOMMENDATIONS_append, " udev-hwdb"]

        # Remove unused DISTRO_FEATURES
        - [DISTRO_FEATURES_remove, "acl alsa argp pcmcia usbgadget
                usbhost opengl ptest multiarch wayland vulkan
                sysvinit"]

        # Enable systemd on dom0
        - [DISTRO_FEATURES_append, " systemd"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]

        # Do not install kernel image to rootfs to decrease initrd size
        - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

        - ["DOMF_ALLOWED_PCPUS", "4-7"]

      layers:
        - "../meta-virtualization"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-dom0"
        - "../meta-xt-common/meta-xt-control-domain"
        - "../meta-xt-rcar/meta-xt-rcar-dom0"
        - "../meta-xt-prod-aos/meta-xt-prod-aos-rcar-control"
        - "../poky/meta-yocto-bsp"
      build_target: core-image-thin-initramfs
      external_src:
        domd: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/"
        domf: "%{YOCTOS_WORK_DIR}/%{DOMF_BUILD_DIR}/tmp/deploy/images/generic-armv8-xt/"
      additional_deps:
        - "%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
        - "%{DOMF_BUILD_DIR}/tmp/deploy/images/generic-armv8-xt/Image"
      target_images:
        - "tmp/deploy/images/generic-armv8-xt/Image"
        - "tmp/deploy/images/generic-armv8-xt/uInitramfs"

  domd:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: https://github.com/xen-troops/meta-renesas.git
        rev: "Renesas-Yocto-v5.1-patched"
      - type: git
        url: "git://git.yoctoproject.org/meta-selinux"
        rev: dunfell
      - type: git
        url: "https://github.com/iusyk/meta-xt-prod-aos.git"
        rev: moulin

    builder:
      type: yocto
      work_dir: "%{DOMD_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMU_CONF
        - [XT_DOM_NAME, "domd"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [XT_DEVICE_TREES, "%{XT_DOMD_DTB_NAME} %{XT_DOMU_DTB_NAME} %{XT_XEN_DTB_NAME}"]
        - [XT_GUEST_INSTALL, "%{XT_GENERIC_DOMU_TAG} %{XT_DOMA_TAG}"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]
        # Machine feature 'multimedia' is used to enable (VSP in domd) and (LOSSY build option in ATF)
        - [MACHINE_FEATURES_append, " multimedia"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]
        - [BOARD_MODEL, "h3ulcb-ab;1.0"]
        - [DOMD_IMAGE_VERSION, "2.0.0"]
        - [DOMD_REF_VERSION, "1.0.0"]
        - [BUNDLE_DOMD_TYPE, "full"]
        - [INITRAMFS_IMAGE, "core-image-tiny-initramfs"]
        - [INITRAMFS_IMAGE_BUNDLE, "0"]
        - [INITRAMFS_FSTYPES, " ext4 cpio.gz"]
        - [IMAGE_FSTYPES_append, " ext4 cpio.gz"]

      build_target: core-image-minimal
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-renesas/meta-rcar-gen3"
        - "../meta-virtualization"
        - "../meta-selinux"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-driver-domain"
        - "../meta-xt-rcar/meta-xt-rcar-fixups"
        - "../meta-xt-rcar/meta-xt-rcar-driver-domain"
        - "../meta-xt-prod-aos/meta-aos-tune"
        - "../meta-xt-prod-aos/meta-xt-prod-aos-rcar-driver-domain"
        - "../meta-aos"
      target_images:
        - "tmp/deploy/images/%{MACHINE}/Image"
        - "tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
        - "tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
        - "tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
        - "tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"

  domf:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "https://github.com/xen-troops/meta-renesas.git"
        rev: "Renesas-Yocto-v5.1-patched"
      - type: git
        url: "git://git.yoctoproject.org/meta-selinux"
        rev: dunfell
      - type: git
        url: "https://github.com/iusyk/meta-xt-prod-aos.git"
        rev: moulin

    builder:
      type: yocto
      work_dir: "%{DOMF_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMU_CONF
        - [XT_DOM_NAME, "domf"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [DISTRO_FEATURES_append, " virtualization"]
        - [XT_DOMU_DTB_NAME, "%{XT_DOMU_DTB_NAME}"]

        # For systemd
        - [DISTRO_FEATURES_append, " systemd"]
        - [DISTRO_FEATURES_BACKFILL_CONSIDERED_append, "sysvinit"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]
        - [VIRTUAL-RUNTIME_initscripts, "systemd-compat-units"]
        - [XT_GUEST_INSTALL, "%{XT_GENERIC_DOMU_TAG} %{XT_DOMA_TAG}"]
        # Machine feature 'multimedia' is used to enable (VSP in domd) and (LOSSY build option in ATF)
        - [MACHINE_FEATURES_append, " multimedia"]

        - [AOS_RUNNER, "crun"]
        - [PREFERRED_PROVIDER_virtual/runc, "runc-opencontainers"]
        # kernel provider
        - [PREFERRED_PROVIDER_virtual/kernel, "linux-generic-armv8"]
        # MACHINE
        - [MACHINE, "generic-armv8-xt"]
        #initramfs configuration
        - [INITRAMFS_IMAGE, "core-image-tiny-initramfs"]
        - [INITRAMFS_IMAGE_BUNDLE, "0"]
        - [INITRAMFS_FSTYPES, "ext4 cpio.gz"]
        - [IMAGE_FSTYPES_append, " ext4"]
        # Image version
        - [DOMF_IMAGE_VERSION, "1.0.1"]
        # Disable optee in meta-xt-images-domx layers
        - [BBMASK_append, "meta-xt-images-domx/recipes-bsp/optee"]
        - [BBMASK_append, "|kernel-module-uvcs-drv|omx-user-module"]
        
      build_target: core-image-minimal 
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-virtualization"
        - "../meta-aos"
        - "../meta-renesas/meta-rcar-gen3"
        - "../meta-xt-prod-aos/meta-xt-prod-aos-rcar-domu"
        - "../meta-linaro/meta-optee"
        - "../meta-xt-common/meta-xt-domx"

      target_images:
        - "tmp/deploy/images/generic-armv8-xt/Image"
  
images:
  full:
    type: gpt
    desc: "Full SD-card/eMMC image"
    partitions:
      boot_a:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "Image": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/Image"
          "uInitramfs": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/uInitramfs"
          "xen": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
          "xenpolicy": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
          "xen.dtb": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
      boot_b:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "Image": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/Image"
          "uInitramfs": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/uInitramfs"
          "xen": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
          "xenpolicy": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
          "xen.dtb": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
      env_part:
        gpt_type: E6D6D379-F507-44C2-A23C-238F2A3DF928
        type: ext4
        size: 32 MiB
      domd_rootfs:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"
      domd_userdata:
        gpt_type: E6D6D379-F507-44C2-A23C-238F2A3DF928
        type: ext4
        size: 6022 MiB        
      domf:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/build-domf/tmp/deploy/images/generic-armv8-xt/core-image-minimal-generic-armv8-xt.ext4"
      domf_userdata:
        gpt_type: E6D6D379-F507-44C2-A23C-238F2A3DF928 
        type: ext4
        size: 6022 MiB

parameters:

  PREBUILT_DDK:
    desc: "Use pre-built GPU drivers"
    "no":
      default: true
      overrides:
        components:
          domd:
            *DDK_SOURCE_OVERRIDES
          domf:
            *DDK_SOURCE_OVERRIDES          

  ENABLE_MM:
    desc: "Enable Multimedia support"
    "no":
      default: true
      overrides:
        components:
          domd:
            builder:
              conf:
                # Mask MMP recipes
                - [BBMASK_append, "|kernel-module-uvcs-drv|omx-user-module"]
  ENABLE_AOS_VIS:
    desc: "Enable non open source aos-vis service"
    "no":
      default: true
    "yes":
      overrides:
        components:
          domd:
            sources:
              - type: git
                url: "https://github.com/aoscloud/meta-aos"
                rev: "4b0f4ea629db039af8cec8f9ea019bb4c9e6d0c7"
            builder:
              layers:
                - "../meta-aos"
              conf:
                - [AOS_VIS_PLUGINS, "telemetryemulatoradapter"]
                - [DISTRO_FEATURES_append, " vis"]
          domf:
            sources:
              - type: git
                url: "https://github.com/aoscloud/meta-aos"
                rev: "4b0f4ea629db039af8cec8f9ea019bb4c9e6d0c7"
            builder:
              layers:
                - "../meta-aos"
              conf:
                - [AOS_VIS_PLUGINS, "telemetryemulatoradapter"]
                - [DISTRO_FEATURES_append, " vis"]

